 //医院
 CREATE TABLE `tb_hospital` (
  `hospital_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name_cn` varchar(200) NOT NULL DEFAULT '',
  `name_native` varchar(200) NOT NULL DEFAULT '',
  `country` tinyint(3) NOT NULL DEFAULT '0',
  `district_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '省市',
  `district_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '市区',
  `district_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '区县',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `status_item_price` tinyint(1) NOT NULL DEFAULT '0',
  `type` int(10) unsigned NOT NULL DEFAULT '0',
  `service_type` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '服务类型:1医疗美容,2综合,3口腔专科,4眼科专科,5皮肤科专科,6美容机构',
  `type_add` int(255) unsigned NOT NULL DEFAULT '1' COMMENT '资本类型:1 公立医院  2 公立医院承包科室  3 民营医院  4 合资医院  5 外资医院',
  `hospital_type` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '医院类型',
  `security` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0 没有保障金 1 有',
  `sole` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0 非独家 1 是独家',
  `level` int(10) unsigned NOT NULL DEFAULT '0',
  `auto_level` int(10) unsigned NOT NULL DEFAULT '0',
  `size_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `auto_size_level` int(10) unsigned NOT NULL DEFAULT '0',
  `tech_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `auto_tech_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `service_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `auto_service_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `hot_level` int(10) unsigned NOT NULL DEFAULT '0',
  `recommend_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `order` int(10) NOT NULL DEFAULT '0',
  `icon` varchar(120) NOT NULL DEFAULT '',
  `founded` date NOT NULL DEFAULT '0000-00-00',
  `chain_cnt` mediumint(5) NOT NULL DEFAULT '0',
  `doctor_cnt` mediumint(5) NOT NULL DEFAULT '0',
  `album_cnt` int(9) NOT NULL DEFAULT '0',
  `item_cnt` mediumint(5) NOT NULL DEFAULT '0',
  `address` varchar(500) NOT NULL DEFAULT '',
  `intro` varchar(500) NOT NULL DEFAULT '',
  `special_intro` varchar(500) NOT NULL DEFAULT '',
  `other_info` varchar(500) NOT NULL DEFAULT '',
  `service_qq` varchar(255) NOT NULL DEFAULT '',
  `service_tel` varchar(255) NOT NULL DEFAULT '' COMMENT '新氧400电话',
  `hospital_tel` varchar(255) NOT NULL DEFAULT '' COMMENT '医院电话',
  `is_modify_tel` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否修改了电话',
  `email` varchar(255) NOT NULL DEFAULT '',
  `business_hours` varchar(500) NOT NULL DEFAULT '',
  `lon` varchar(50) NOT NULL DEFAULT '',
  `lat` varchar(50) NOT NULL DEFAULT '',
  `view_cnt` int(11) NOT NULL DEFAULT '0',
  `certified` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `certified_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '认证用户ID',
  `certified_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '认证时间',
  `is_open` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开放',
  `yewu` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '医院业务',
  `website` varchar(200) NOT NULL DEFAULT '' COMMENT '官网',
  `source` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '资料来源',
  `source_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '来源id',
  `dianping_score` int(11) NOT NULL DEFAULT '0' COMMENT '点评总分',
  `dianping_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '点评数',
  `dianping_create` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为点评生成',
  `service_weixin` varchar(100) NOT NULL DEFAULT '' COMMENT '微信',
  `service_weibo` varchar(100) NOT NULL DEFAULT '' COMMENT '微博',
  `verify_status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '审核状态',
  `modify_yn` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否修改 1已修改 0未修改',
  `create_from` int(2) NOT NULL DEFAULT '0' COMMENT '生成途径:1约惠',
  `hospital_title` int(5) NOT NULL DEFAULT '0' COMMENT '医院称号',
  `bd_id` int(10) NOT NULL DEFAULT '0' COMMENT 'BD经理uid',
  `bd_display_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否显示bd信息',
  `operation_manager_id` int(10) NOT NULL DEFAULT '0' COMMENT '运营经理id',
  `operation_display_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '运营经理是否显示',
  `tj_order` int(10) NOT NULL DEFAULT '0' COMMENT '推荐顺序',
  `tel_view_num` int(10) NOT NULL DEFAULT '0' COMMENT '查看咨询电话数',
  `institution_type` int(2) NOT NULL DEFAULT '1' COMMENT '机构类型 1医院 2美容院',
  `calendar_group_cnt` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '回复日历数',
  `calendar_score` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '满意度和',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `paystages` int(4) NOT NULL DEFAULT '0',
  `finalpay` int(4) NOT NULL DEFAULT '0',
  `paystagesdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '支持白条时间',
  `finalpaydate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '支持尾款时间',
  `cloud_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是云诊所',
  `weight` tinyint(3) unsigned DEFAULT '1' COMMENT '是否降权 1不降权 0降权',
  `business_qualification_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '医疗广告许可证(工商资质) 1有 0没有',
  PRIMARY KEY (`hospital_id`),
  KEY `idx_order` (`status`,`order`),
  KEY `idx_hotlevel` (`hot_level`),
  KEY `idx_name` (`name_cn`,`district_2`,`certified`,`status`),
  KEY `certified_id` (`certified_id`)
) ENGINE=InnoDB AUTO_INCREMENT=27068 DEFAULT CHARSET=utf8


//医生
CREATE TABLE `tb_doctor` (
  `doctor_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name_cn` varchar(200) NOT NULL DEFAULT '',
  `name_native` varchar(200) NOT NULL DEFAULT '',
  `type` tinyint(3) NOT NULL DEFAULT '0' COMMENT '1=公立一级2=公立二级3=公立三级4=民营0=其他',
  `country` tinyint(3) NOT NULL DEFAULT '0',
  `district_1` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '省市',
  `district_2` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '市区',
  `district_3` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '区县',
  `gender` tinyint(1) unsigned NOT NULL DEFAULT '2',
  `status` tinyint(1) NOT NULL DEFAULT '0',
  `level` int(10) unsigned NOT NULL DEFAULT '0',
  `auto_level` int(10) unsigned NOT NULL DEFAULT '0',
  `hospital_id` int(10) unsigned NOT NULL DEFAULT '0',
  `sole` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0 非独家 1 是独家',
  `icon` varchar(120) NOT NULL DEFAULT '',
  `career_day` date NOT NULL DEFAULT '0000-00-00',
  `position` int(8) NOT NULL DEFAULT '0',
  `title` tinyint(3) NOT NULL DEFAULT '0',
  `education` mediumint(5) NOT NULL DEFAULT '0',
  `order` tinyint(3) NOT NULL DEFAULT '0',
  `intro` varchar(500) NOT NULL DEFAULT '',
  `professional_exp` varchar(1000) NOT NULL DEFAULT '',
  `learning_exp` varchar(1000) NOT NULL DEFAULT '',
  `professional_ass` varchar(1000) NOT NULL DEFAULT '',
  `hot_level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `bianhao` varchar(30) NOT NULL DEFAULT '' COMMENT '执业医师编号',
  `is_open` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否开放',
  `source` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '数据来源',
  `source_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '来源id',
  `certified` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否认证',
  `certified_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '认证用户ID',
  `certified_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '认证时间',
  `dianping_score` int(11) NOT NULL DEFAULT '0' COMMENT '点评总分',
  `dianping_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '点评数',
  `dianping_create` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为点评生成',
  `verify_status` tinyint(2) NOT NULL DEFAULT '1' COMMENT '审核状态',
  `modify_yn` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否修改 1已修改 0未修改',
  `create_from` int(2) NOT NULL DEFAULT '0' COMMENT '生成途径:1约惠',
  `bd_id` int(10) DEFAULT '0',
  `bd_display_yn` tinyint(1) NOT NULL DEFAULT '1',
  `operation_manager_id` int(10) NOT NULL DEFAULT '0',
  `operation_display_yn` tinyint(1) NOT NULL DEFAULT '0',
  `calendar_group_cnt` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '恢复日历数',
  `calendar_score` int(11) unsigned NOT NULL DEFAULT '0' COMMENT '满意度和',
  `tj_order` int(10) NOT NULL DEFAULT '0' COMMENT '推荐顺序',
  `occup_type` int(2) NOT NULL DEFAULT '1' COMMENT '职业类型 1医生 2美容师 ',
  `group_id` int(10) NOT NULL DEFAULT '0' COMMENT '日历id',
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id',
  `post_id` int(10) NOT NULL DEFAULT '0' COMMENT '帖子id',
  `every_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '1:填了日历、产品、帖子中的任何一个 0都没填',
  `relation_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '名医关联时间',
  `pub_order` int(10) NOT NULL DEFAULT '0',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `paystages` int(4) NOT NULL DEFAULT '0',
  `finalpay` int(4) NOT NULL DEFAULT '0',
  `paystagesdate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '支持白条时间',
  `finalpaydate` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '支持尾款时间',
  `sort_record` int(1) NOT NULL DEFAULT '0' COMMENT '置顶顺序',
  `is_top` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否置顶',
  `doctor_operate` tinyint(4) DEFAULT '0' COMMENT '是否开通医生工作台：0，未开通，1开通',
  `doctor_operate_time` int(11) DEFAULT '0' COMMENT '医生工作台开通时间|关闭时间',
  PRIMARY KEY (`doctor_id`),
  KEY `idx_order` (`status`,`order`),
  KEY `idx_hospital` (`hospital_id`,`status`,`order`),
  KEY `idx_name` (`name_cn`,`district_2`,`certified`,`status`),
  KEY `idx_isopen` (`status`,`is_open`) USING BTREE,
  KEY `certified_id` (`certified_id`)
) ENGINE=InnoDB AUTO_INCREMENT=72888 DEFAULT CHARSET=utf8;


//医院产品
CREATE TABLE `tb_discount_product` (
  `pid` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `product_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '类型',
  `product_status` int(2) NOT NULL DEFAULT '0' COMMENT '状态 0 后台审核中 1 审核通过 -1 审核未通过',
  `hospital_id` int(10) NOT NULL DEFAULT '0' COMMENT '医院id',
  `title` varchar(500) NOT NULL DEFAULT '' COMMENT '标题',
  `attach_title` varchar(250) NOT NULL DEFAULT '' COMMENT '副标题',
  `total_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '总数',
  `sold_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '卖出数',
  `auto_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '启动数',
  `each_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '每人限购数量',
  `price_online_min` int(10) NOT NULL DEFAULT '0' COMMENT '在线预约价,最小值',
  `price_online` int(10) NOT NULL DEFAULT '0' COMMENT '在线预约价',
  `price_boutique` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '精选价格',
  `price_origin` int(10) NOT NULL DEFAULT '0' COMMENT '医院原价',
  `price_deposit` int(10) NOT NULL DEFAULT '0' COMMENT '定金',
  `price_deposit_admin` int(10) NOT NULL DEFAULT '0' COMMENT '管理员定金',
  `price_full_money` int(10) NOT NULL DEFAULT '0' COMMENT '全款支付价钱',
  `subsidy_money` smallint(6) NOT NULL DEFAULT '0' COMMENT '补贴金额',
  `price_purchase` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '采购价',
  `valid_time` tinyint(3) NOT NULL DEFAULT '0' COMMENT '有效期',
  `valid_time_auto` int(10) NOT NULL DEFAULT '0' COMMENT '自定义有效期,秒',
  `valid_date_auto` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '自定义有效时间',
  `appointment` varchar(50) NOT NULL DEFAULT '' COMMENT '服务承诺',
  `special_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否特卖 1 是特卖 2 申请特卖中 0 不是特卖 -1未通过',
  `usetime` varchar(200) NOT NULL DEFAULT '' COMMENT '使用时间',
  `img_cover` varchar(200) NOT NULL DEFAULT '' COMMENT '封面图片',
  `img_cover1` varchar(200) NOT NULL DEFAULT '' COMMENT '我的预约图片',
  `order_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '预约数',
  `order_auto_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '自定义随机订单数',
  `case_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '案例数',
  `case_score` int(10) NOT NULL DEFAULT '0' COMMENT '案例满意度',
  `start_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '特卖开始时间',
  `end_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '特卖结束时间',
  `price_special_min` int(10) NOT NULL DEFAULT '0' COMMENT '特卖价格,最小值',
  `price_special` int(10) NOT NULL DEFAULT '0' COMMENT '特卖价格',
  `deposit_special` int(11) DEFAULT NULL COMMENT '定金 特卖定金',
  `special_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '特卖数量',
  `special_sold_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '特卖卖出数',
  `view_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '浏览量',
  `close_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否下架 1已下架 0已上架',
  `display_yn` int(2) NOT NULL DEFAULT '1' COMMENT '是否删除',
  `xy_money_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否可使用氧分',
  `xy_money_exchange` int(10) NOT NULL DEFAULT '0' COMMENT '允许氧分兑换的最大金额，0全额兑换',
  `xy_money_deposit_yn` tinyint(2) NOT NULL DEFAULT '0',
  `xy_money_deposit_exchange` int(10) NOT NULL DEFAULT '0',
  `xy_money_full_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '全款支付是否支持氧分兑换',
  `xy_money_full_exchange` int(10) NOT NULL DEFAULT '0' COMMENT '全款支持氧分兑换上额',
  `topic_id` int(10) NOT NULL DEFAULT '0' COMMENT '特卖ID',
  `micro_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否微整形',
  `operation_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为手术',
  `featured_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是精选产品 默认0不是 1是精选产品',
  `deposit_boutique` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '精选定金',
  `promotion_id` smallint(6) NOT NULL DEFAULT '0' COMMENT '推广id',
  `inject_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否注射',
  `laser_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否激光',
  `reduce_product_type` tinyint(1) NOT NULL DEFAULT '1' COMMENT '减产品数方式:1支付回调减2下订单减',
  `order_expire_time` int(10) NOT NULL DEFAULT '0' COMMENT '订单有效时间,秒',
  `on_sale_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为抢购',
  `on_sale_preheat_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '抢购预热时间',
  `on_sale_start_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '抢购开始时间',
  `on_sale_end_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '抢购结束时间',
  `on_sale_cnt` int(10) NOT NULL DEFAULT '0' COMMENT '抢购产品数量',
  `pay_stages_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否支持分期付款',
  `cash_back` int(10) NOT NULL DEFAULT '0' COMMENT '发日记返现金额',
  `cash_back_special` int(10) NOT NULL DEFAULT '0' COMMENT '特卖返现金额',
  `wxmall_only` tinyint(1) NOT NULL DEFAULT '0' COMMENT '只在新氧VIP中显示，VIP特权产品',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '建立时间',
  `bd_create_uid` int(5) unsigned NOT NULL DEFAULT '0' COMMENT 'BD创建者uid',
  `create_source` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '1 医院创建 2 新氧创建',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '修改时间',
  `topic_time` int(11) NOT NULL DEFAULT '0' COMMENT '置顶时间',
  `template_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '视图模板类型 0=老模板;1=6.2.9新模板',
  `price_cost` decimal(11,2) NOT NULL DEFAULT '0.00' COMMENT '成本价',
  `gong_yn` tinyint(2) NOT NULL DEFAULT '0' COMMENT '是否公立 1是0否',
  `fan_money` int(10) NOT NULL DEFAULT '0' COMMENT '返巨款',
  `fan_money_endtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `is_top` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被置顶',
  `sort_record` int(10) NOT NULL DEFAULT '0' COMMENT '置顶排序序号',
  `hide_flag` tinyint(1) NOT NULL DEFAULT '0' COMMENT '隐藏操作标志 0 未操作 1 操作',
  `first_close_yn_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '产品第一次上架时间',
  `uid` bigint(20) unsigned zerofill DEFAULT NULL COMMENT '商品首次创建 uid',
  PRIMARY KEY (`pid`),
  KEY `idx_hospital` (`hospital_id`,`product_status`,`create_date`),
  KEY `promotion_id` (`promotion_id`),
  KEY `idx_title` (`title`(255))
) ENGINE=InnoDB AUTO_INCREMENT=114247 DEFAULT CHARSET=utf8 COMMENT='医院产品表';
 tb_order | CREATE TABLE `tb_order` (
  `order_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `product_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '产品类型',
  `product_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '产品ID',
  `promotion_id` smallint(6) NOT NULL DEFAULT '0' COMMENT '推广id: 0商城 1特卖 2精选',
  `amount` int(10) NOT NULL DEFAULT '0' COMMENT '购买数量',
  `amount_original` int(11) unsigned NOT NULL DEFAULT '1' COMMENT '拆单前,原始购买数量',
  `order_id_original` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '拆单前原始订单号',
  `uid` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '购买人',
  `mobile` bigint(11) unsigned NOT NULL DEFAULT '0' COMMENT '手机',
  `price_origin` int(10) NOT NULL DEFAULT '0' COMMENT '原始价格',
  `price_purchase` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '采购价',
  `price_discuss` int(10) NOT NULL DEFAULT '0' COMMENT '协商价格',
  `special_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否特卖：1是特卖，2不是特卖',
  `on_sale_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为抢购',
  `pay_full_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否是全款支付',
  `hospital_id` int(10) NOT NULL DEFAULT '0' COMMENT '医院id',
  `doctor_id` int(10) NOT NULL DEFAULT '0' COMMENT '订单所属唯一医生ID',
  `order_owner_type` tinyint(3) NOT NULL DEFAULT '1' COMMENT '订单所有者类型1医院2医生',
  `admin_close` tinyint(1) NOT NULL DEFAULT '0' COMMENT '管理员关闭',
  `hospital_close` tinyint(1) NOT NULL DEFAULT '0' COMMENT '医院关闭',
  `price_deposit` int(10) NOT NULL DEFAULT '0' COMMENT '支付定金',
  `account_deposit` decimal(10,2) NOT NULL DEFAULT '0.00',
  `discount_amount` decimal(8,2) NOT NULL DEFAULT '0.00' COMMENT 'app下单立减 多少元',
  `discount_code_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否使用了优惠码:1-已使用;0-未使用',
  `xy_money_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否使用氧分',
  `xy_money` int(10) NOT NULL DEFAULT '0' COMMENT '使用的氧分数',
  `xy_money_exchange` int(10) NOT NULL DEFAULT '0' COMMENT '氧分兑换的价钱',
  `xy_money_deposit_yn` tinyint(2) NOT NULL DEFAULT '0',
  `xy_money_deposit` int(10) NOT NULL DEFAULT '0',
  `xy_money_deposit_exchange` int(10) NOT NULL DEFAULT '0',
  `channel_code` varchar(200) NOT NULL DEFAULT '' COMMENT '渠道代码',
  `address` varchar(300) NOT NULL DEFAULT '' COMMENT '收货地址',
  `topic_id` int(10) NOT NULL DEFAULT '0' COMMENT '特卖ID',
  `micro_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为微整形',
  `operation_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为手术',
  `group_id` int(10) NOT NULL DEFAULT '0' COMMENT '日记id',
  `cash_back` int(10) NOT NULL DEFAULT '0' COMMENT '返现金额',
  `device_id` int(10) NOT NULL DEFAULT '0' COMMENT '设备ID',
  `sys` tinyint(2) NOT NULL DEFAULT '0',
  `lver` varchar(20) NOT NULL DEFAULT '',
  `app_id` int(10) NOT NULL DEFAULT '0',
  `app_channel` int(10) NOT NULL DEFAULT '0' COMMENT 'app渠道',
  `status` int(2) NOT NULL DEFAULT '1' COMMENT '状态',
  `goto_alipay_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否跳转到过支付宝页面',
  `code_id` int(10) NOT NULL DEFAULT '0' COMMENT '优惠码id',
  `pay_type` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '渠道',
  `pay_type_name` varchar(100) NOT NULL DEFAULT '' COMMENT '渠道名称',
  `pay_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '支付状态',
  `pay_return` varchar(2000) NOT NULL DEFAULT '' COMMENT '渠道返回完整信息',
  `create_ip` varchar(30) NOT NULL DEFAULT '' COMMENT '购买ip',
  `pay_ip` varchar(30) NOT NULL DEFAULT '' COMMENT '付款ip',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '状态更新时间',
  `pay_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '支付完成时间',
  `expire_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '订单过期时间',
  `inverse_date` int(11) NOT NULL DEFAULT '0',
  `pay_sys` tinyint(2) NOT NULL DEFAULT '0' COMMENT '支付终端 0网站1手机',
  `rollback_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否回滚',
  `xysource` int(10) NOT NULL DEFAULT '0' COMMENT '订单来源',
  `wxmall` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '新氧微商城',
  `wsid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '新氧微商ID',
  `invite_uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '邀请者UID',
  `address_id` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '收货地址id',
  `price_cut` int(10) NOT NULL DEFAULT '0' COMMENT '满减金额',
  `insurance_amount` int(11) NOT NULL DEFAULT '0' COMMENT '保险金额单位分',
  `insurance_number` varchar(100) NOT NULL DEFAULT '' COMMENT '保单号：验证后产生',
  `insurance_status` tinyint(2) NOT NULL DEFAULT '0' COMMENT '0未支付 1支付成功等待审核 2审核通过 3审核不通过 4 退款 5 已验证 6 已过期 7先支付后关联受益人 8 单独支付',
  `insurance_amount_payer` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '保险支付者类型：0未支付 1用户 2新氧 3医院',
  `insurance_type` tinyint(2) NOT NULL DEFAULT '0' COMMENT '保险类型：1、微整 2、眼部 3、鼻部',
  `balancepay_code_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '尾款使用红包id',
  `balancepay_cut_price` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '尾款红包抵扣金额单位元',
  `insurance_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'db_passport.tb_user_insurance投保人id',
  `provider_id` int(10) NOT NULL DEFAULT '0' COMMENT '供货商id',
  `price_cost` int(10) NOT NULL DEFAULT '0' COMMENT '美淘产品成本价:单位分',
  `is_tuan` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '是否开团商品订单',
  `tuan_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '用户开团id',
  `sphinx_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '自动更新时间',
  PRIMARY KEY (`order_id`),
  KEY `idx_uid` (`uid`,`product_type`,`inverse_date`),
  KEY `idx_uid_st` (`uid`,`product_type`,`pay_status`,`inverse_date`),
  KEY `idx_status` (`pay_status`,`status`),
  KEY `idx_invite_uid` (`invite_uid`),
  KEY `idx_wxmall` (`wxmall`),
  KEY `idx_doctorid` (`doctor_id`),
  KEY `idx_pid_pay` (`product_id`,`pay_status`,`pay_date`),
  KEY `sphinx_update` (`sphinx_update`),
  KEY `idx_hospital` (`hospital_id`,`status`,`pay_status`,`create_date`),
  KEY `idx_tuan_id` (`pay_status`,`tuan_id`,`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=254831262 DEFAULT CHARSET=utf8 ;

 tb_post | CREATE TABLE `tb_post` (
  `post_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL DEFAULT '',
  `post_type` mediumint(6) NOT NULL DEFAULT '0',
  `uid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `summary` varchar(255) NOT NULL DEFAULT '',
  `view_cnt` int(11) NOT NULL DEFAULT '0',
  `up_cnt` int(10) NOT NULL DEFAULT '0',
  `ding_cnt` int(11) NOT NULL DEFAULT '0',
  `down_cnt` int(10) NOT NULL DEFAULT '0',
  `comment_cnt` int(11) NOT NULL DEFAULT '0',
  `locked_yn` tinyint(1) NOT NULL DEFAULT '0',
  `display_yn` tinyint(1) NOT NULL DEFAULT '1',
  `top_yn` tinyint(1) NOT NULL DEFAULT '1',
  `marrow_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否精华',
  `waterfall_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为瀑布流',
  `related_id` int(11) unsigned NOT NULL DEFAULT '0',
  `sys` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `app_id` int(10) NOT NULL DEFAULT '0' COMMENT '应用ID',
  `sys_ver` varchar(10) NOT NULL DEFAULT '' COMMENT '版本',
  `anonymous` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `lou` int(10) unsigned NOT NULL DEFAULT '1',
  `score` int(10) NOT NULL DEFAULT '0',
  `money` int(11) NOT NULL DEFAULT '0' COMMENT '氧分',
  `source` tinyint(3) NOT NULL DEFAULT '0',
  `forbid_uid` bigint(20) unsigned NOT NULL DEFAULT '0' COMMENT '禁贴uid',
  `del_uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '删除者',
  `del_admin_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '删除者',
  `private` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否私密发帖',
  `private_uid` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '私密uid',
  `cover_img` varchar(200) NOT NULL DEFAULT '' COMMENT '封面图片',
  `img_cnt` smallint(5) NOT NULL DEFAULT '0' COMMENT '图片数量',
  `report_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为投诉帖子',
  `calendar_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为新的日记',
  `topic_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否讨论帖子 1是 0否',
  `pgc_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为pgc帖子 1是 0否',
  `pgc_img` varchar(200) NOT NULL DEFAULT '' COMMENT 'pgc图片',
  `weight` int(11) NOT NULL DEFAULT '0' COMMENT '人为权重',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `down_time` int(11) NOT NULL DEFAULT '0' COMMENT '沉帖时间',
  `lou_update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '楼主最后更新时间',
  `ip` varchar(20) NOT NULL DEFAULT '',
  `sphinx_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '自动更新时间',
  `event_id` int(10) NOT NULL DEFAULT '0' COMMENT '关联活动id',
  `reply_locked_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '回帖锁，1表示锁 0不锁',
  `post_video_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为视频贴，1是 0不是',
  `post_video_img` varchar(200) NOT NULL DEFAULT '' COMMENT '视频封面',
  `post_video_url` varchar(200) NOT NULL DEFAULT '' COMMENT '视频地址',
  `reward_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否支持打赏:1 支持',
  PRIMARY KEY (`post_id`),
  KEY `idx_related_id` (`related_id`),
  KEY `idx_uid` (`uid`,`create_date`),
  KEY `idx_topic` (`topic_yn`,`display_yn`,`private`,`locked_yn`) USING BTREE,
  KEY `post_type` (`post_type`,`display_yn`),
  KEY `sphinx_update` (`sphinx_update`),
  KEY `idx_event` (`event_id`,`display_yn`) USING BTREE,
  KEY `display_yn` (`display_yn`) USING BTREE,
  KEY `uid` (`uid`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=13300982 DEFAULT CHARSET=utf8 |;

 CREATE TABLE `tb_post_content` (
  `post_id` int(11) unsigned NOT NULL DEFAULT '0',
  `content` text,
  `video` varchar(1000) NOT NULL DEFAULT '' COMMENT '视频代码',
  `group_id` varchar(100) NOT NULL DEFAULT '0' COMMENT '关联的日历id',
  `pid` varchar(100) NOT NULL DEFAULT '0' COMMENT '关联产品id',
  PRIMARY KEY (`post_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

 CREATE TABLE `tb_calendar_group` (
  `group_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `uid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `item` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '日历项目',
  `hospital_id` int(10) NOT NULL DEFAULT '0' COMMENT '医院id',
  `doctor_id` int(10) NOT NULL DEFAULT '0' COMMENT '医院id',
  `price` int(10) NOT NULL DEFAULT '0' COMMENT '价钱',
  `day` date NOT NULL DEFAULT '0000-00-00' COMMENT '日历日期',
  `status` tinyint(3) NOT NULL DEFAULT '1' COMMENT '状态',
  `calendar_cnt` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '日记数',
  `post_cnt` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '帖子数',
  `post_open_cnt` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '公开帖子数',
  `favor_cnt` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '帖子喜欢数',
  `view_cnt` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '帖子浏览数量',
  `comment_cnt` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '帖子评论数',
  `last_post_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后帖子id',
  `last_open_post_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后公开的post_id',
  `last_calendar_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '最后记录id',
  `sys` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '系统平台',
  `app_id` int(10) NOT NULL DEFAULT '0' COMMENT '应用ID',
  `sys_ver` varchar(10) NOT NULL DEFAULT '' COMMENT '版本',
  `ip` varchar(30) NOT NULL DEFAULT '',
  `hot_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否热门 1是0否',
  `baidu_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否加入百度健康',
  `menu1_id` int(10) NOT NULL DEFAULT '0',
  `menu2_id` int(10) NOT NULL DEFAULT '0',
  `micro_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否微整形',
  `country` tinyint(3) NOT NULL DEFAULT '0',
  `district_1` int(10) NOT NULL DEFAULT '0',
  `district_2` int(10) NOT NULL DEFAULT '0',
  `district_3` int(10) NOT NULL DEFAULT '0',
  `order_id` bigint(20) NOT NULL DEFAULT '0' COMMENT '订单id',
  `pid` int(10) NOT NULL DEFAULT '0' COMMENT '产品id',
  `cash_back_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否已返现',
  `pre_top_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '预置顶',
  `pre_top_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '预置顶时间',
  `hospital_yn` tinyint(1) NOT NULL DEFAULT '2' COMMENT '是否是医院案例 1是 2否',
  `doctor_yn` tinyint(1) NOT NULL DEFAULT '2' COMMENT '是否是医生案例 1是 2否',
  `group_type` tinyint(1) NOT NULL DEFAULT '0' COMMENT '日历类型 1新 0老',
  `report_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否投诉 1是 0否',
  `weight` smallint(6) NOT NULL DEFAULT '0' COMMENT '手动权重',
  `relation_yn` tinyint(1) NOT NULL DEFAULT '1' COMMENT '1.关联医院医生 0取消关联',
  `is_top` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否被置顶 0 不置顶 1置顶',
  `top_sort` int(10) NOT NULL DEFAULT '0' COMMENT '置顶排序序号',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `lou_update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '楼主最后回复时间',
  `update_date_top` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'app置顶更新时间',
  `group_video_yn` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否为视频日历，1是 0不是',
  PRIMARY KEY (`group_id`),
  KEY `idx_uid` (`uid`,`item`,`day`),
  KEY `idx_date` (`update_date`,`create_date`),
  KEY `idx_list` (`status`,`post_open_cnt`,`hot_yn`,`hospital_yn`,`doctor_yn`),
  KEY `idx_item` (`item`,`status`,`post_open_cnt`,`hospital_yn`,`doctor_yn`),
  KEY `idx_hospital` (`hospital_id`,`status`,`post_cnt`,`post_open_cnt`),
  KEY `idx_doctor` (`doctor_id`,`status`,`post_cnt`,`post_open_cnt`),
  KEY `idx_pid` (`pid`,`status`,`post_open_cnt`) USING BTREE,
  KEY `idx_order` (`order_id`,`status`,`post_open_cnt`) USING BTREE,
  KEY `idx_time` (`update_date_top`,`update_date`,`hospital_yn`,`doctor_yn`)
) ENGINE=InnoDB AUTO_INCREMENT=5988463 DEFAULT CHARSET=utf8 COMMENT='日历项目表';


 CREATE TABLE `tb_calendar` (
  `calendar_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` int(10) unsigned NOT NULL DEFAULT '0',
  `uid` bigint(20) unsigned NOT NULL DEFAULT '0',
  `item` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '记录项目',
  `day` date NOT NULL DEFAULT '0000-00-00' COMMENT '记录日期',
  `day_num` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '第几天',
  `post_id` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '关联帖子',
  `status` tinyint(3) NOT NULL DEFAULT '0' COMMENT '状态',
  `sys` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '系统平台',
  `app_id` int(10) NOT NULL DEFAULT '0' COMMENT '应用ID',
  `sys_ver` varchar(10) NOT NULL DEFAULT '' COMMENT '版本',
  `ip` varchar(30) NOT NULL DEFAULT '',
  `create_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `update_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`calendar_id`),
  KEY `idx_item` (`item`,`day`),
  KEY `idx_item_days` (`item`,`day_num`),
  KEY `idx_uid_calendar` (`uid`,`item`,`day`),
  KEY `idx_groupid` (`group_id`,`day`,`create_date`),
  KEY `index_id_st_cr` (`post_id`,`status`,`create_date`)
) ENGINE=InnoDB AUTO_INCREMENT=1204914 DEFAULT CHARSET=utf8 COMMENT='日历表';




